### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jaan143** [dle-modules/DLE-TagFace#2]
# Описание ошибки:

- При каких условиях воспроизводится ошибка
- Страница, на которой наблюдается ошибка
- Вносились ли модификации в движок
- Версия DLE: 10.3
- Версия PHP: 5.6

does it support DLE 12.0 ?

**Comment by pafnuty** [comment]
Hi @jaan143
Unfortunately current version of TagFace does not support DLE 12.x
